"""empty message

Revision ID: e0d1393f54de
Revises: ac68c8ae4bbc
Create Date: 2025-01-23 10:08:52.811679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0d1393f54de'
down_revision = 'ac68c8ae4bbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               nullable=False)
        batch_op.alter_column('image_url',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=256),
               nullable=False)
        batch_op.alter_column('new_price',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('section',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=128),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('section',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('new_price',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('image_url',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
